### ISSUE TITLE
0x05  __setattr__

### ISSUE THREAD

**Issue by jwz-ecust** [wangshunping/read_requests#5]
如果按照你说的在__init__中对method作限制， 只会在开始时候对method做一次判断，如果后面改掉method就不会检查在不在_METHODS了。可能__setattr__的好处就在这吧
大神写很不错！🍺🍺🍺

**Comment by leisurelicht** [comment]
哦，我觉得是为了可以在实例化的时候不用立刻给method赋值

**Comment by linxidd** [comment]
初始化的时候并不赋值啊，还是self.method默认的None，判断放到__init__里真的有用吗？只有对实例中的属性赋值的时候判断才有意义，我感觉这才是使用__setattr__的意义。
